In [1]:
!kaggle datasets download -d unanimad/us-election-2020

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/abhinowo/.kaggle/kaggle.json'

Downloading us-election-2020.zip to /home/abhinowo/Documents/LearningProject/PythonDataAnalytics/electionSeries/lp-1
100%|█████████████████████████████████████████| 429k/429k [00:00<00:00, 779kB/s]
100%|█████████████████████████████████████████| 429k/429k [00:00<00:00, 767kB/s]

In [2]:
!unzip us-election-2020.zip

Archive:  us-election-2020.zip
  inflating: governors_county.csv
  inflating: governors_county_candidate.csv
  inflating: governors_state.csv
  inflating: house_candidate.csv
  inflating: house_state.csv
  inflating: president_county.csv
  inflating: president_county_candidate.csv
  inflating: president_state.csv
  inflating: senate_county.csv
  inflating: senate_county_candidate.csv
  inflating: senate_state.csv

# Introduction
The goal of the notebook is to analyze the results of Americal elections in 2020. Its kinda messy code but i hope you guys who read it get the point of what i'm trying to do. Any kind of feedback is welcome! Reach me out

## 1.1 Data preparation

so first step. import useful library here :)

In [29]:
# Basic libraries
import numpy as np
import pandas as pd

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.figure_factory as ff
import plotly.express as px
import warnings
warnings.filterwarnings("ignore")

In [4]:
# read data
df_governors = pd.read_csv('./data_input/governors_county_candidate.csv')
df_president = pd.read_csv('./data_input/president_county_candidate.csv')
df_senate = pd.read_csv('./data_input/senate_county_candidate.csv')

In [5]:
#lets take a look at the data 
df_governors

              state             county        candidate party   votes    won
0          Delaware        Kent County      John Carney   DEM   44352   True
1          Delaware        Kent County  Julianne Murray   REP   39332  False
2          Delaware        Kent County  Kathy DeMatteis   IPD    1115  False
3          Delaware        Kent County    John Machurek   LIB     616  False
4          Delaware  New Castle County      John Carney   DEM  191678   True
...             ...                ...              ...   ...     ...    ...
5140  West Virginia     Wyoming County      Jim Justice   REP    6941   True
5141  West Virginia     Wyoming County      Ben Salango   DEM    1240  False
5142  West Virginia     Wyoming County   Erika Kolenich   LIB      86  False
5143  West Virginia     Wyoming County       Danny Lutz   MNP      53  False
5144  West Virginia     Wyoming County        Write-ins   WRI       0  False

[5145 rows x 6 columns]

In [6]:
df_president

          state             county      candidate party  total_votes    won
0      Delaware        Kent County      Joe Biden   DEM        44552   True
1      Delaware        Kent County   Donald Trump   REP        41009  False
2      Delaware        Kent County   Jo Jorgensen   LIB         1044  False
3      Delaware        Kent County  Howie Hawkins   GRN          420  False
4      Delaware  New Castle County      Joe Biden   DEM       195034   True
...         ...                ...            ...   ...          ...    ...
32172   Arizona    Maricopa County      Write-ins   WRI         1331  False
32173   Arizona      Mohave County   Donald Trump   REP        78535   True
32174   Arizona      Mohave County      Joe Biden   DEM        24831  False
32175   Arizona      Mohave County   Jo Jorgensen   LIB         1302  False
32176   Arizona      Mohave County      Write-ins   WRI           37  False

[32177 rows x 6 columns]

In [7]:
df_senate

          state             county         candidate party  total_votes
0      Delaware        Kent County     Lauren Witzke   REP        38571
1      Delaware        Kent County       Mark Turley   IPD         1553
2      Delaware        Kent County      Nadine Frost   LIB          958
3      Delaware  New Castle County     Lauren Witzke   REP        80081
4      Delaware  New Castle County       Mark Turley   IPD         4277
...         ...                ...               ...   ...          ...
14120   Georgia       Worth County         Ed Tarver   DEM           17
14121   Georgia       Worth County      John Fortuin   GRN           15
14122   Georgia       Worth County  Valencia Stovall   IND           15
14123   Georgia       Worth County    Michael Greene   IND           14
14124   Georgia       Worth County         Write-ins   WRI            0

[14125 rows x 5 columns]

In [8]:
## Lets take a look into more detail on president data
df_president.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32177 entries, 0 to 32176
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   state        32177 non-null  object
 1   county       32177 non-null  object
 2   candidate    32177 non-null  object
 3   party        32177 non-null  object
 4   total_votes  32177 non-null  int64
 5   won          32177 non-null  bool
dtypes: bool(1), int64(1), object(4)
memory usage: 1.3+ MB

In [9]:
# We have 3112 rows and 8 columns and theres no null values, lets see the data based on the first 5 rows of total_votes by DESC. and we can remove the index column
df_president_new = df_president.sort_values(by='total_votes', ascending=False).head().reset_index(drop=True)
df_president_new

        state              county     candidate party  total_votes    won
0  California  Los Angeles County     Joe Biden   DEM      3028885   True
1    Illinois         Cook County     Joe Biden   DEM      1725973   True
2  California  Los Angeles County  Donald Trump   REP      1145530  False
3     Arizona     Maricopa County     Joe Biden   DEM      1040774   True
4     Arizona     Maricopa County  Donald Trump   REP       995665  False

In [10]:
# Now we need to check total votes group by each party
df_president.groupby('party')['total_votes'].sum().reset_index().sort_values(by='total_votes', ascending=False)

   party  total_votes
7    DEM     82046434
20   REP     74585705
12   LIB      1874183
9    GRN       407508
25   WRI       254274
11   IND       126908
0    ALI        88158
19   PSL        85453
6    CST        61730
2    ASP        25256
15   NON        14079
22   SWP         6791
24   UTY         6647
3    BAR         5949
17   PRG         5367
18   PRO         4834
23   UNA         3513
14   LLP         1372
8    GOP         1175
10   IAP          815
13   LLC          668
16   OTH          546
1    APV          409
21   SEP          196
4    BFP          141
5    BMP          126

In [11]:
df_president.head()

      state             county      candidate party  total_votes    won
0  Delaware        Kent County      Joe Biden   DEM        44552   True
1  Delaware        Kent County   Donald Trump   REP        41009  False
2  Delaware        Kent County   Jo Jorgensen   LIB         1044  False
3  Delaware        Kent County  Howie Hawkins   GRN          420  False
4  Delaware  New Castle County      Joe Biden   DEM       195034   True

In [12]:
# now we shall look by state and county and see the total votes for each party
df_presiden_vote = df_president.groupby(['state','county','party'])['total_votes'].sum().reset_index().sort_values(by='total_votes',ascending=False)
df_presiden_vote

            state              county party  total_votes
1585   California  Los Angeles County   DEM      3028885
5451     Illinois         Cook County   DEM      1725973
1589   California  Los Angeles County   REP      1145530
615       Arizona     Maricopa County   DEM      1040774
617       Arizona     Maricopa County   REP       995665
...           ...                 ...   ...          ...
14200    Michigan  Montmorency County   ALI            0
14192    Michigan       Monroe County   WRI            0
8917        Maine             Addison   WRI            0
26122     Vermont           Middlesex   BMP            0
21723   Tennessee     Campbell County   WRI            0

[29980 rows x 4 columns]

In [13]:
df_presiden_vote = df_president.groupby(['state', 'county', 'party'])['total_votes'].sum().reset_index()
df_presiden_most_vote = df_presiden_vote.set_index(['state', 'county']).sort_values(by='total_votes', ascending=False)
df_presiden_most_vote.head()

                              party  total_votes
state      county
California Los Angeles County   DEM      3028885
Illinois   Cook County          DEM      1725973
California Los Angeles County   REP      1145530
Arizona    Maricopa County      DEM      1040774
           Maricopa County      REP       995665

In [14]:
df_presiden_state = df_presiden_vote.set_index(['state', 'county'])
df_presiden_state.head()

                       party  total_votes
state   county
Alabama Autauga County   DEM         7503
        Autauga County   LIB          350
        Autauga County   REP        19838
        Autauga County   WRI           79
        Baldwin County   DEM        24578

In [15]:
#list of 3 most voted party
selected_parties = ['DEM', 'REP','LIB']
df_selected_parties = df_presiden_vote[df_presiden_vote['party'].isin(selected_parties)]
# df_selected_parties.head()

#pivot the DF
df_pivot = df_selected_parties.pivot_table(index=['state','county'], columns='party', values='total_votes')
# df_pivot.reset_index(inplace=True)
df_pivot.head()

party                     DEM   LIB    REP
state   county
Alabama Autauga County   7503   350  19838
        Baldwin County  24578  1229  83544
        Barbour County   4816    68   5622
        Bibb County      1986    74   7525
        Blount County    2640   209  24711

In [16]:
# Group by 'state' and 'county' and sum the total votes for each party
df_county_totals = df_selected_parties.groupby(['state', 'county', 'party'])['total_votes'].sum().unstack(fill_value=0)
df_county_totals.head()

party                     DEM   LIB    REP
state   county
Alabama Autauga County   7503   350  19838
        Baldwin County  24578  1229  83544
        Barbour County   4816    68   5622
        Bibb County      1986    74   7525
        Blount County    2640   209  24711

In [19]:
df_state_totals = df_selected_parties.groupby(['state', 'party'])['total_votes'].sum().unstack(fill_value=0)

# Display the DataFrame
df_state_totals.head()

party            DEM     LIB      REP
state
Alabama       849648   25176  1441168
Alaska        153405    8896   189892
Arizona      1672143   51465  1661686
Arkansas      423932   13133   760647
California  11109764  187885  6005961

In [20]:
# Let's sort it from descending order based on the total votes, just to know the first state that has the most votes overall for each party 
# Group by 'state' and 'party' and sum the total votes for each party
df_state_total_votes = df_selected_parties.groupby(['state', 'party'])['total_votes'].sum().unstack(fill_value=0)

# Sort by total_votes in descending order
df_state_total_votes = df_state_total_votes.sort_values(by=['DEM', 'REP', 'LIB'], ascending=False)

# Display the DataFrame
df_state_total_votes

party                      DEM     LIB      REP
state
California            11109764  187885  6005961
Florida                5297045   70324  5668731
Texas                  5259126  126243  5890347
New York               5244006   60369  3250230
Illinois               4253153   76122  2823926
Pennsylvania           3459923   79397  3378263
Michigan               2804040   60381  2649852
North Carolina         2684292   48678  2758773
Ohio                   2679165   67569  3154834
New Jersey             2608335   31677  1883274
Georgia                2473633   62229  2461854
Virginia               2413568   64761  1962430
Massachusetts          2382202   47013  1167202
Washington             2369612   80500  1584651
Maryland               1985023   33488   976414
Colorado               1804352   52460  1364607
Minnesota              1717077   34976  1484065
Arizona                1672143   51465  1661686
Wisconsin              1630673   38491  1610065
Oregon                 1340383   41582   958448
Missouri               1253014   41205  1718736
Indiana                1242495   58900  1729852
Tennessee              1143913   29883  1852948
South Carolina         1091541   27916  1385103
Connecticut            1080680   20227   715291
Louisiana               856034   21645  1255776
Alabama                 849648   25176  1441168
Kentucky                772474   26234  1326646
Iowa                    759061   19637   897672
Nevada                  703486   14783   669890
Utah                    560282   38447   865140
Kansas                  558669   29797   758100
Mississippi             539398    8026   756764
Oklahoma                503890   24731  1020280
New Mexico              501614   12585   401894
Maine                   430473   14005   359899
New Hampshire           424921   13235   365654
Arkansas                423932   13133   760647
Nebraska                374583   20283   556846
Hawaii                  366130    5539   196864
District of Columbia    317323    2036    18586
Rhode Island            306210    5047   199837
Delaware                296268    5000   200603
Idaho                   287021   16404   554119
Montana                 244786   15252   343602
Vermont                 242820    3608   112704
West Virginia           235984   10687   545382
Alaska                  153405    8896   189892
South Dakota            150471   11095   261043
North Dakota            114902    9393   235595
Wyoming                  73491    5768   193559

In [21]:
# Lets see total votes for DEM based on the state
df_dem_votes = df_state_total_votes['DEM'].sort_values(ascending=False).iloc[:3]
df_dem_votes

state
California    11109764
Florida        5297045
Texas          5259126
Name: DEM, dtype: int64

In [22]:
# Lets see total votes for LIB based on the state
df_lib_votes = df_state_total_votes['LIB'].sort_values(ascending=False).iloc[:3]
df_lib_votes

state
California    187885
Texas         126243
Washington     80500
Name: LIB, dtype: int64

In [23]:
# Lets see total votes for REP based on the state
df_rep_votes = df_state_total_votes['REP'].sort_values(ascending=False).iloc[:3]
df_rep_votes

state
California    6005961
Texas         5890347
Florida       5668731
Name: REP, dtype: int64

In [1]:
# We shall move to visualization
df_vis = df_presiden_vote['DEM']*100/df_presiden_vote['REP']+df_presiden_vote['DEM']
df_vis.head()

NameError: name 'df_presiden_vote' is not defined

In [ ]:
fig = px.choropleth(df_presiden_most_vote, 
                    locations="usa_state_code", 
                    color = "percent_democrat",
                    locationmode = 'USA-states', 
                    hover_name="state",
                    range_color=[25,75],
                    color_continuous_scale = 'RdBu',#blues
                    scope="usa",
                    title='2020 USA Election: Percent of Population Voting for the Democratic Party')
fig.show()